### ISSUE TITLE
Modify handling or relation models: One for all

### ISSUE THREAD

**Issue by Kuraao** [arreason/CategoryLearning#13]
- We should have only one relation model
- The relation model should take a triplet (source, target, label) as input

**Comment by Previsou** [comment]
Unless I missed something huge, the codebase is far from ready for it. All our structures are using simple DAG, not multi-graph. We currently have no way to retain, match nor use relation labels in the init dataset, neither in further inference steps.

We are currently trying to use triple input (src, dst, rel), mapped to (src, dst, RelModel(src, dst, rel)) whie all our codebase expects (src, dst) x RelModels mapped to {(src, r(src,dst)) for r in RelModels }

NB: the changes is doable, obvisouly. But it seems somewhat massive and intrusive imho.
Would love your input on this @Kuraao

**Comment by Kuraao** [comment]
Nope, the edges can have labels (in fact they do in the current version of the CompositionGraph: the labels are the names of the relation models in use).

From what I see what needs to be modified is mostly the RelationCache. It should take as input only one relation generator instead of a dict of generators (see generators argument of __init__)

The match method of the RelationCache already takes into account labels given as probability vectors. Several relation labels linking a source and a target may exist (Several relations may also exist in the cache of course, and only the score of the best one for each label is kept from what I see).
